### your site title here

title: Bir genç geliştiricinin kişisel blogu.
author: Süleyman Poyraz
email: zaryob.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kişisel blogum.
#baseurl: /


twitter_username: pyrz_suleyman
github_username: Zaryob

sass:
    style: compressed

# Tracker
#analytics: UA-83979019-1

collections:
  - external_feed

exclude:
- README.md

include:
- _pages


exclude: [vendor]

permalink: /:categories/:title/


markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
