### your site title here

title: Bir genç geliştiricinin kişisel blogu.
author: Süleyman Poyraz
email: zaryob.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kişisel blogum.
url: localhost::8080
  #baseurl: /


twitter_username: pyrz_suleyman
github_username: Zaryob

sass:
    style: compressed
    post: compressed

# Tracker
google_analytics: "G-M6NQ8DV1XP"

exclude:
- README.md

include:
- _pages


exclude: [vendor]

permalink: /:categories/:title/


markdown:           kramdown
paginate:           15
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
