# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed

<<<<<<< HEAD
title: Bir genç geliştiricinin kişisel blogu.
author: Süleyman Poyraz
email: zaryob.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kişisel blogum.
baseurl: /


twitter_username: pyrz_suleyman
github_username: Zaryob

sass:
    style: compressed

# Tracker
#analytics: UA-83979019-1
=======

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: Süleyman'ın Blogu                          # the main title

tagline: Suleyman Poyraz'ın kişisel çalışma ve paylaşma alanı.  # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
    Ben Süleyman Poyraz. Karmaşık düşüncelerini topladığı zaman yararlı işler
    yapabilen bir gencim.


# Replace with the website url, e.g. 'https://username.github.io'
url: 'https://zaryob.github.io'

author: Zaryob                  # change to your full name

avatar: /assets/img/sample/avatar.jpg   # support internet resources

github:
  username: Zaryob              # change to your github username

twitter:
  username: pyrz_suleyman            # change to your twitter username

social:
  name: Suleyman Poyraz                  # it will shows as the copyright owner in Footer
  email: zaryob.dev@gmail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/pyrz_suleyman      # change to your twitter homepage
    - https://github.com/Zaryob       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/suleyman-poyraz/

# google_site_verification: google_meta_tag_verification # change to your verification string

#--------------------------


# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/Istanbul

google_analytics:
  id: ''          # Fill with your Google Analytics ID
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: ''
    cache: false  # pv data local cache, good for the users from GFW area.

disqus:
  comments: false  # boolean type, the global switch for posts comments.
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dual

# boolean type, global switch for ToC in posts.
toc: true

paginate: 10

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# or you think you're smart enough to change other relevant URLs within this template.
permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      tab_active: Tags
      location: Tag
      breadcrumb:
        -
          label: Anasayfa
          url: /
        -
          label: Etiketler
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      tab_active: Kategoriler
      location: Kategori
      breadcrumb:
        -
          label: Anasayfa
          url: /
        -
          label: Kategoriler
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        -
          label: Anasayfa
          url: /


sass:
  sass_dir: /assets/css
  style: compressed
>>>>>>> 5a28cf7bf7c0a68162b9c6b5c95736f00290c087

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp,
            optgroup, option, colgroup, caption,
            thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor        # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

<<<<<<< HEAD
include:
- _pages


exclude: [vendor]

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
=======
sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
>>>>>>> 5a28cf7bf7c0a68162b9c6b5c95736f00290c087
