### your site title here

title: Bir genç geliştiricinin kişisel blogu.

baseurl:
sass:
    style: compressed

# Tracker
analytics: UA-83979019-1

plugins:
   - jekyll-sitemap

exclude:
- README.md

include:
- _pages
