version: '3'
services:
  jekyll:
      image: jekyll/jekyll:3.8.5
      environment:
        - JEKYLL_ENV=development
      command: jekyll serve --watch --force_polling --verbose
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll:cached
          - ./vendor/bundle:/usr/local/bundle:cached
